"""updated records table with geom

Revision ID: 45afb1995afb
Revises: 87faad3cb3ab
Create Date: 2025-11-29 08:25:27.631797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '45afb1995afb'
down_revision: Union[str, None] = '87faad3cb3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('geometry', Geometry(from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'geometry')
    # ### end Alembic commands ###
