"""updated records table

Revision ID: 87faad3cb3ab
Revises: 589a978ddb4b
Create Date: 2025-11-29 08:03:48.120642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87faad3cb3ab'
down_revision: Union[str, None] = '589a978ddb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('record_type', sa.String(), nullable=False))
    op.alter_column('records', 'extra_props',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'extra_props',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('records', 'record_type')
    # ### end Alembic commands ###
