"""updated records with identifier

Revision ID: 8a12a0b4ce3f
Revises: 45afb1995afb
Create Date: 2025-11-29 09:58:56.842878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8a12a0b4ce3f'
down_revision: Union[str, None] = '45afb1995afb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'identifier')
    # ### end Alembic commands ###
