"""removed algo table

Revision ID: bdb9a99826b9
Revises: e81c3fcf61d0
Create Date: 2025-11-30 09:12:04.037094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdb9a99826b9'
down_revision: Union[str, None] = 'e81c3fcf61d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('algorithms')
    op.drop_table('credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('available_credits', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='credits_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='credits_pkey')
    )
    op.create_table('algorithms',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('algorithms_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dag_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='algorithms_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('credits', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('algorithm_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], name='transactions_algorithm_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transactions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    # ### end Alembic commands ###
